package com.miaadrajabi.downloader

import android.content.Context
import android.util.Log
import java.io.File
import java.io.IOException
import java.io.RandomAccessFile
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicInteger
import kotlin.math.max
import kotlin.coroutines.coroutineContext
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import okhttp3.Call
import okhttp3.OkHttpClient

/**
 * 1. Core download queue manager stub that will be expanded in later steps.
 * 2. Holds the immutable DownloadConfig generated by the builder or direct input.
 */
class MobileDownloadManager private constructor(
    context: Context,
    private val config: DownloadConfig,
    private val resumeInterrupted: Boolean = false
) {

    private val appContext = context.applicationContext ?: context
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val notificationHelper = DownloadNotificationHelper(appContext, config.notification)
    private val listeners: List<DownloadListener> = config.listeners + notificationHelper.listener
    private val storageResolver = StorageResolver(appContext, config.storage)
    private val scheduler = DownloadScheduler(appContext, config.scheduler)
    private val pendingDestinations = ConcurrentHashMap<String, StorageResolution>()
    private val activeSessions = ConcurrentHashMap<String, DownloadSession>()
    private val pausedStates = ConcurrentHashMap<String, PausedState>()
    private val chunkStateSnapshots = ConcurrentHashMap<String, MutableMap<Int, ChunkStateData>>()
    private val lastProgress = ConcurrentHashMap<String, Long>()
    private val httpClient = OkHttpClient()
    private val chunkedDownloader = ChunkedDownloader(httpClient)
    private val activeDownloads = AtomicInteger(0)
    private val trackedIds = ConcurrentHashMap.newKeySet<String>()
    private val reservedIds = ConcurrentHashMap.newKeySet<String>()
    private val terminalSuccess = ConcurrentHashMap<String, Boolean>()
    private val suppressFinishJobs = ConcurrentHashMap.newKeySet<Job>()
    private val attemptGeneration = ConcurrentHashMap<String, Long>()
    private val artifactMeta = ConcurrentHashMap<String, ArtifactValidators>()
    private val checkpointBytes = ConcurrentHashMap<String, Long>()
    private val sessionLock = Any()

    init {
        DownloadNotificationRegistry.helper = notificationHelper
        DownloadManagerRegistry.manager = this
        DownloadConfigStore.save(appContext, config)
        restorePausedStates()
        if (resumeInterrupted) {
            recoverInterruptedDownloads()
        }
    }

    private fun restorePausedStates() {
        val restored = DownloadConfigStore.loadAllPausedStates(appContext)
        restored.forEach { pausedData ->
            val chunkList = pausedData.chunkStates
            val completed = if (chunkList.isNotEmpty()) {
                chunkList.totalCompletedBytes()
            } else {
                pausedData.completedBytes
            }
            pausedStates[pausedData.handleId] = PausedState(
                request = pausedData.request,
                resolution = pausedData.resolution,
                completedBytes = completed,
                chunkStates = chunkList
            )
            pendingDestinations[pausedData.handleId] = pausedData.resolution
            if (chunkList.isNotEmpty()) {
                chunkStateSnapshots[pausedData.handleId] =
                    chunkList.associateBy { it.index }.toMutableMap()
            }
            lastProgress[pausedData.handleId] = completed
        }
    }

    private fun currentChunkStates(handleId: String): List<ChunkStateData> {
        return chunkStateSnapshots[handleId]?.values
            ?.map { it.copy() }
            ?.sortedBy { it.index }
            ?: emptyList()
    }

    /**
     * 3. Exposes the immutable configuration for diagnostics and logging.
     */
    val configuration: DownloadConfig
        get() = config

    /**
     * 4. Adds a new download request to the active queue and starts transfer immediately.
     */
    fun enqueue(incoming: DownloadRequest): DownloadHandle {
        val request = try {
            byteWindowOf(incoming.rangeStart, incoming.rangeEndInclusive)
            incoming.copy(
                expectedChecksum = validatedChecksum(
                    incoming.expectedChecksum,
                    incoming.checksumAlgorithm
                )
            )
        } catch (error: IllegalArgumentException) {
            val handle = DownloadHandle(id = incoming.id, source = incoming.url)
            listeners.forEach { it.onFailed(handle, error) }
            return handle
        }
        synchronized(sessionLock) {
            if (activeSessions.containsKey(request.id) || !reservedIds.add(request.id)) {
                return DownloadHandle(id = request.id, source = request.url)
            }
            if (pausedStates.containsKey(request.id) && resume(request.id)) {
                reservedIds.remove(request.id)
                return DownloadHandle(id = request.id, source = request.url)
            }
        }
        var published = false
        try {
            val preview = storageResolver.resolve(request, dryRun = true)
            val path = canonicalPath(preview.file)
            val owner = pathOwner(path, request.id)
            val record = DownloadRecoveryStore.load(appContext, request.id)
            when (
                admitDownload(
                    sameIdState = record?.state,
                    sameIdSameArtifact = record == null || sameArtifact(record.request, request),
                    pathOwnerState = owner?.state,
                    pathOwnerIsSameId = owner?.id == request.id
                )
            ) {
                Admission.RejectBusy -> {
                    val handle = DownloadHandle(id = request.id, source = request.url)
                    listeners.forEach { listener ->
                        listener.onFailed(
                            handle,
                            IllegalStateException("Destination is owned by an active download")
                        )
                    }
                    return handle
                }
                Admission.ReplaceFromZero -> {
                    dropAbandoned(owner?.id ?: record?.id)
                }
                Admission.ReuseActive -> {
                    if (record != null && startFromRecord(record)) {
                        return DownloadHandle(id = record.id, source = record.request.url)
                    }
                    if (activeSessions.containsKey(request.id)) {
                        return DownloadHandle(id = request.id, source = request.url)
                    }
                }
                Admission.StartFresh -> Unit
            }
            val resolution = storageResolver.resolve(request)
            pendingDestinations[request.id] = resolution
            trackDownload(request.id)

            val handle = DownloadHandle(
                id = request.id,
                source = request.url
            )

            listeners.forEach { it.onQueued(handle) }
            val progressTrackingListener = object : DownloadListener {
                override fun onProgress(handle: DownloadHandle, progress: DownloadProgress) {
                    lastProgress[handle.id] = progress.bytesDownloaded
                }
            }
            chunkStateSnapshots.remove(handle.id)
            val chunkStateUpdater: (ChunkStateData) -> Unit = { state ->
                val map = chunkStateSnapshots.getOrPut(handle.id) { ConcurrentHashMap() }
                map[state.index] = state
            }
            val session = DownloadSession(request, resolution, Job(), CallTracker())
            val job = scope.launch(session.job) {
                runDownloadWithRetry(
                    request,
                    handle,
                    resolution,
                    startOffset = 0L,
                    callTracker = session.callTracker,
                    extraListeners = listOf(progressTrackingListener),
                    existingChunkStates = emptyList(),
                    chunkStateUpdater = chunkStateUpdater
                )
            }
            activeSessions[handle.id] = session.copy(job = job)
            watchSession(handle.id, job)
            published = true
            return handle
        } catch (error: Exception) {
            if (!published) {
                Log.e(TAG, "Download could not start for ${request.fileName}", error)
                markDownloadFinished(request.id)
                val handle = DownloadHandle(id = request.id, source = request.url)
                listeners.forEach { it.onFailed(handle, error) }
                return handle
            }
            throw error
        } finally {
            reservedIds.remove(request.id)
        }
    }

    /**
     * 5. Provides visibility into where a request will land without mutating files.
     */
    fun previewDestination(request: DownloadRequest): StorageResolution {
        return storageResolver.resolve(request, dryRun = true)
    }

    /**
     * 6. Returns the prepared destination for an enqueued request, if available.
     */
    fun resolvedDestination(handleId: String): StorageResolution? {
        return pendingDestinations[handleId]
    }

    /**
     * 7. Schedules the request by leveraging WorkManager or AlarmManager.
     */
    fun schedule(request: DownloadRequest, scheduleTime: ScheduleTime? = config.scheduler.exactStartTime) {
        scheduler.schedule(request, scheduleTime)
    }

    /**
     * 8. Cancels any scheduled job associated with the request id.
     */
    fun cancelScheduled(handleId: String) {
        scheduler.cancel(handleId)
    }

    /**
     * 9. Attempts to pause an in-flight download. Returns true if a job was cancelled.
     */
    fun pause(handleId: String): Boolean {
        val session = synchronized(sessionLock) {
            val current = activeSessions[handleId] ?: return false
            // Keep the active count until resume or stop. The completion handler must not
            // treat this pause as a finished download.
            suppressFinishJobs.add(current.job)
            attemptGeneration[handleId] = (attemptGeneration[handleId] ?: 0L) + 1L
            val chunkStates = currentChunkStates(handleId)
            val completedBytes = if (chunkStates.isNotEmpty()) {
                chunkStates.totalCompletedBytes()
            } else {
                lastProgress[handleId] ?: current.resolution.file.length()
            }
            pausedStates[handleId] = PausedState(
                request = current.request,
                resolution = current.resolution,
                completedBytes = completedBytes,
                chunkStates = chunkStates
            )
            activeSessions.remove(handleId)
            current
        }
        val paused = pausedStates[handleId]
        if (paused != null) {
            persistRecord(paused.request, paused.resolution, DownloadRecovery.PAUSED, attemptGeneration[handleId] ?: 0L, true)
            DownloadConfigStore.savePausedState(
                appContext,
                handleId,
                paused.request,
                paused.resolution,
                paused.completedBytes,
                paused.chunkStates
            )
        }
        val handle = DownloadHandle(handleId, session.request.url)
        session.job.cancel(CancellationException("Paused by user"))
        session.callTracker.cancelAll()
        if (activeSessions[handleId] == null) {
            listeners.forEach { it.onPaused(handle) }
        }
        return true
    }

    /**
     * 10. Resumes a paused download from the last saved offset.
     */
    fun resume(handleId: String): Boolean {
        val handle = synchronized(sessionLock) {
            if (activeSessions.containsKey(handleId)) return false
            val paused = pausedStates.remove(handleId) ?: return false
            // The paused record stays on disk until the download completes, so a process
            // death during resume can restore the same offset.
            trackDownload(handleId)
            val started = DownloadHandle(id = paused.request.id, source = paused.request.url)
            val progressTrackingListener = object : DownloadListener {
                override fun onProgress(handle: DownloadHandle, progress: DownloadProgress) {
                    lastProgress[handle.id] = progress.bytesDownloaded
                }
            }
            val chunkStates = paused.chunkStates
            val resumeBytes = if (chunkStates.isNotEmpty()) {
                chunkStates.totalCompletedBytes()
            } else {
                paused.completedBytes
            }
            lastProgress[handleId] = resumeBytes
            chunkStateSnapshots[handleId] = chunkStates.associateBy { it.index }.toMutableMap()
            val chunkStateUpdater: (ChunkStateData) -> Unit = { state ->
                val map = chunkStateSnapshots.getOrPut(handleId) { ConcurrentHashMap() }
                map[state.index] = state
            }
            val session = DownloadSession(paused.request, paused.resolution, Job(), CallTracker())
            val job = scope.launch(session.job) {
                runDownloadWithRetry(
                    paused.request,
                    started,
                    paused.resolution,
                    startOffset = resumeBytes,
                    callTracker = session.callTracker,
                    extraListeners = listOf(progressTrackingListener),
                    existingChunkStates = chunkStates,
                    chunkStateUpdater = chunkStateUpdater
                )
            }
            activeSessions[handleId] = session.copy(job = job)
            watchSession(handleId, job)
            started
        }
        listeners.forEach { it.onResumed(handle) }
        return true
    }

    /**
     * 11. Stops and forgets an active/paused download entirely.
     */
    fun stop(handleId: String): Boolean {
        val stopped = synchronized(sessionLock) {
            val session = activeSessions.remove(handleId)
            val paused = pausedStates.remove(handleId)
            if (session == null && paused == null) {
                return false
            }
            if (session != null) {
                suppressFinishJobs.remove(session.job)
            }
            attemptGeneration[handleId] = (attemptGeneration[handleId] ?: 0L) + 1L
            DownloadRecoveryStore.delete(appContext, handleId)
            pendingDestinations.remove(handleId)
            chunkStateSnapshots.remove(handleId)
            session to paused
        }
        DownloadConfigStore.removePausedState(appContext, handleId)
        val session = stopped.first
        val paused = stopped.second
        if (session != null) {
            session.callTracker.cancelAll()
            session.job.cancel(CancellationException("Stopped by user"))
            return true
        }
        if (paused != null) {
            listeners.forEach { it.onCancelled(DownloadHandle(handleId, paused.request.url)) }
            terminalSuccess[handleId] = true
            markDownloadFinished(handleId)
            return true
        }
        return false
    }

    /**
     * 9. Shuts down resources and cancels background scope for cleanup.
     */
    fun shutdown() {
        scope.coroutineContext.cancel()
        DownloadManagerRegistry.manager = null
    }

    internal fun hasRunningDownloads(): Boolean {
        return activeSessions.isNotEmpty() || activeDownloads.get() > 0
    }

    internal fun clearPendingNotificationUpdates() {
        notificationHelper.clearPendingUpdates()
    }

    /**
     * Runs the request on this manager and waits until it completes, pauses, or stops.
     * Returns false only when the transfer failed after its own retries. User pause and
     * user stop return true so a scheduler does not start the same download again.
     */
    internal suspend fun enqueueAndAwait(request: DownloadRequest): Boolean {
        enqueue(request)
        activeSessions[request.id]?.job?.join()
        return terminalSuccess.remove(request.id) ?: true
    }

    /**
     * Drops this temporary manager without clearing a manager that was already in use.
     */
    internal fun discardKeeping(
        previousManager: MobileDownloadManager?,
        previousHelper: DownloadNotificationHelper?
    ) {
        scope.coroutineContext.cancel()
        if (DownloadManagerRegistry.manager === this) {
            DownloadManagerRegistry.manager = previousManager
        }
        if (DownloadNotificationRegistry.helper === notificationHelper) {
            DownloadNotificationRegistry.helper = previousHelper
        }
    }

    private fun watchSession(handleId: String, job: Job) {
        job.invokeOnCompletion {
            val current = activeSessions[handleId]
            if (current != null && current.job != job) {
                return@invokeOnCompletion
            }
            activeSessions.remove(handleId)
            lastProgress.remove(handleId)
            chunkStateSnapshots.remove(handleId)
            if (!suppressFinishJobs.remove(job)) {
                markDownloadFinished(handleId)
            }
        }
    }

    private fun trackDownload(handleId: String) {
        if (trackedIds.add(handleId)) {
            activeDownloads.incrementAndGet()
        }
    }

    private suspend fun runDownloadWithRetry(
        request: DownloadRequest,
        handle: DownloadHandle,
        resolution: StorageResolution,
        startOffset: Long = 0L,
        callTracker: CallTracker? = null,
        extraListeners: List<DownloadListener> = emptyList(),
        existingChunkStates: List<ChunkStateData> = emptyList(),
        chunkStateUpdater: ((ChunkStateData) -> Unit)? = null
    ) {
        val policy = config.retryPolicy
        var attempt = 1
        var delayMs = policy.initialDelayMillis
        var plannedChunkStates = existingChunkStates
        var currentStartOffset = startOffset
        var useSingleStream = false
        if (!coroutineContext.isActive || pausedStates.containsKey(handle.id)) {
            return
        }
        val generation = nextGeneration(handle.id)
        DownloadRecoveryStore.load(appContext, handle.id)?.let { saved ->
            artifactMeta[handle.id] = saved.validators()
        }
        terminalSuccess.remove(handle.id)
        persistRecord(request, resolution, DownloadRecovery.RUNNING, generation, true)
        fun noteInterrupt(coroutineActive: Boolean): DownloadInterrupt {
            val interrupt = classifyDownloadInterrupt(
                coroutineActive,
                pausedStates.containsKey(handle.id),
                activeSessions.containsKey(handle.id)
            )
            if (interrupt == DownloadInterrupt.StoppedByUser) {
                listeners.forEach { it.onCancelled(handle) }
                terminalSuccess[handle.id] = true
            }
            return interrupt
        }
        while (attempt <= policy.maxAttempts) {
            try {
                val allListeners = listeners + extraListeners
                allListeners.forEach { it.onStarted(handle) }
                val downloadResult = chunkedDownloader.download(
                    request,
                    resolution,
                    handle,
                    config,
                    allListeners,
                    currentStartOffset,
                    callTracker,
                    plannedChunkStates,
                    chunkStateUpdater,
                    singleStream = useSingleStream,
                    validators = artifactMeta[handle.id],
                    onCheckpoint = {
                        if (attemptGeneration[handle.id] == generation) {
                            persistRecord(request, resolution, DownloadRecovery.RUNNING, generation, false)
                        }
                    }
                )
                rememberValidators(handle.id, downloadResult)

                if (config.integrity.verifyFileSize ||
                    config.integrity.verifyChecksum ||
                    config.integrity.verifyApkStructure ||
                    config.integrity.verifyContentType ||
                    config.integrity.verifyApkSignature) {

                    val window = byteWindowOf(request.rangeStart, request.rangeEndInclusive)
                    val integrityResult = FileIntegrityVerifier.verifyFile(
                        file = resolution.file,
                        config = config.integrity,
                        request = request,
                        expectedSize = window.sliceLength(downloadResult.totalBytes),
                        contentType = downloadResult.contentType,
                        context = appContext
                    )

                    if (!integrityResult.isValid) {
                        val errorMessage = "File integrity validation failed: ${integrityResult.errors.joinToString(", ")}"
                        Log.e("MobileDownloadManager", errorMessage)

                        if (resolution.file.exists()) {
                            val deleted = resolution.file.delete()
                            if (deleted) {
                                Log.d("MobileDownloadManager", "Deleted corrupted file: ${resolution.file.absolutePath}")
                            } else {
                                Log.w("MobileDownloadManager", "Failed to delete corrupted file: ${resolution.file.absolutePath}")
                            }
                        }

                        chunkStateSnapshots.remove(handle.id)
                        lastProgress.remove(handle.id)

                        throw IntegrityValidationException(
                            message = errorMessage,
                            errors = integrityResult.errors,
                            file = resolution.file
                        )
                    }
                }

                if (config.installer.promptOnCompletion) {
                    DownloadInstaller.maybePromptInstall(appContext, resolution.file, config.installer)
                }
                listeners.forEach { it.onCompleted(handle) }
                pendingDestinations.remove(handle.id)
                pausedStates.remove(handle.id)
                DownloadConfigStore.removePausedState(appContext, handle.id)
                if (attemptGeneration[handle.id] == generation) {
                    DownloadRecoveryStore.delete(appContext, handle.id)
                }
                terminalSuccess[handle.id] = true
                return
            } catch (restart: SingleStreamRestartException) {
                if (useSingleStream || !coroutineContext.isActive) {
                    val interrupt = noteInterrupt(coroutineContext.isActive)
                    if (interrupt != DownloadInterrupt.ContinueRetry) {
                        return
                    }
                    if (attempt >= policy.maxAttempts) {
                        listeners.forEach { it.onFailed(handle, restart) }
                        pendingDestinations.remove(handle.id)
                        terminalSuccess[handle.id] = false
                        markAbandoned(request, resolution, generation)
                        return
                    }
                    listeners.forEach { it.onRetry(handle, attempt) }
                    if (!delayUnlessInterrupted(delayMs) { noteInterrupt(it) }) {
                        return
                    }
                    delayMs = (delayMs * policy.backoffMultiplier).toLong().coerceAtLeast(1_000L)
                    attempt++
                } else {
                    Log.w(
                        "MobileDownloadManager",
                        "Range was not honored for ${handle.id}; restarting from byte zero",
                        restart
                    )
                    resetPartial(resolution.file, handle.id)
                    plannedChunkStates = emptyList()
                    currentStartOffset = 0L
                    useSingleStream = true
                    artifactMeta.remove(handle.id)
                    if (attemptGeneration[handle.id] == generation) {
                        persistRecord(request, resolution, DownloadRecovery.RUNNING, generation, false)
                    }
                }
            } catch (error: IntegrityValidationException) {
                pausedStates.remove(handle.id)
                DownloadConfigStore.removePausedState(appContext, handle.id)
                if (attempt >= policy.maxAttempts) {
                    listeners.forEach { it.onFailed(handle, error) }
                    pendingDestinations.remove(handle.id)
                    terminalSuccess[handle.id] = false
                    markAbandoned(request, resolution, generation)
                    return
                } else {
                    listeners.forEach { it.onRetry(handle, attempt) }
                    plannedChunkStates = emptyList()
                    currentStartOffset = 0L
                    chunkStateSnapshots.remove(handle.id)
                    lastProgress.remove(handle.id)
                    artifactMeta.remove(handle.id)
                    useSingleStream = true
                    if (attemptGeneration[handle.id] == generation) {
                        persistRecord(request, resolution, DownloadRecovery.RUNNING, generation, false)
                    }
                    if (!delayUnlessInterrupted(delayMs) { noteInterrupt(it) }) {
                        return
                    }
                    delayMs = (delayMs * policy.backoffMultiplier).toLong().coerceAtLeast(1_000L)
                    attempt++
                }
            } catch (error: IOException) {
                val interrupt = noteInterrupt(coroutineContext.isActive)
                if (interrupt != DownloadInterrupt.ContinueRetry) {
                    return
                }
                if (attempt >= policy.maxAttempts) {
                    listeners.forEach { it.onFailed(handle, error) }
                    pendingDestinations.remove(handle.id)
                    terminalSuccess[handle.id] = false
                    markAbandoned(request, resolution, generation)
                    return
                } else {
                    if (attemptGeneration[handle.id] == generation) {
                        persistRecord(request, resolution, DownloadRecovery.RETRY_WAIT, generation, false)
                    }
                    listeners.forEach { it.onRetry(handle, attempt) }
                    plannedChunkStates = currentChunkStates(handle.id)
                    val lastProgressBytes = lastProgress[handle.id] ?: 0L
                    currentStartOffset = if (lastProgressBytes > 0) lastProgressBytes else currentStartOffset
                    if (!delayUnlessInterrupted(delayMs) { noteInterrupt(it) }) {
                        return
                    }
                    delayMs = (delayMs * policy.backoffMultiplier).toLong().coerceAtLeast(1_000L)
                    attempt++
                }
            } catch (cancel: CancellationException) {
                noteInterrupt(coroutineContext.isActive)
                return
            } catch (error: Throwable) {
                listeners.forEach { it.onFailed(handle, error) }
                pendingDestinations.remove(handle.id)
                terminalSuccess[handle.id] = false
                markAbandoned(request, resolution, generation)
                return
            }
        }
    }

    private suspend fun delayUnlessInterrupted(
        delayMs: Long,
        noteInterrupt: (Boolean) -> DownloadInterrupt
    ): Boolean {
        return try {
            delay(delayMs)
            true
        } catch (cancel: CancellationException) {
            noteInterrupt(coroutineContext.isActive)
            false
        }
    }

    internal suspend fun awaitRecovered() {
        activeSessions.values.map { it.job }.forEach { job -> job.join() }
    }

    private fun recoverInterruptedDownloads() {
        DownloadRecoveryStore.loadAll(appContext).forEach { record ->
            if (record.state == DownloadRecovery.PAUSED) {
                rememberPaused(record)
                return@forEach
            }
            if (record.state !in DownloadRecovery.RESUMABLE_AFTER_RESTART) {
                return@forEach
            }
            pausedStates.remove(record.id)
            if (!activeSessions.containsKey(record.id)) {
                startFromRecord(record)
            }
        }
    }

    private fun rememberPaused(record: DownloadRecoveryRecord) {
        if (pausedStates.containsKey(record.id) || activeSessions.containsKey(record.id)) return
        pausedStates[record.id] = PausedState(
            request = record.request,
            resolution = record.resolution,
            completedBytes = record.completedBytes,
            chunkStates = record.chunkStates
        )
        pendingDestinations[record.id] = record.resolution
        if (record.chunkStates.isNotEmpty()) {
            chunkStateSnapshots[record.id] = record.chunkStates.associateBy { it.index }.toMutableMap()
        }
        lastProgress[record.id] = record.completedBytes
        artifactMeta[record.id] = record.validators()
    }

    private fun startFromRecord(record: DownloadRecoveryRecord): Boolean {
        if (activeSessions.containsKey(record.id)) return false
        pausedStates.remove(record.id)
        artifactMeta[record.id] = record.validators()
        trackDownload(record.id)
        val handle = DownloadHandle(id = record.request.id, source = record.request.url)
        val chunkStates = record.chunkStates
        val resumeBytes = if (chunkStates.isNotEmpty()) {
            chunkStates.totalCompletedBytes()
        } else {
            record.completedBytes
        }
        lastProgress[record.id] = resumeBytes
        if (chunkStates.isNotEmpty()) {
            chunkStateSnapshots[record.id] = chunkStates.associateBy { it.index }.toMutableMap()
        }
        pendingDestinations[record.id] = record.resolution
        val progressTrackingListener = object : DownloadListener {
            override fun onProgress(handle: DownloadHandle, progress: DownloadProgress) {
                lastProgress[handle.id] = progress.bytesDownloaded
            }
        }
        val chunkStateUpdater: (ChunkStateData) -> Unit = { state ->
            val map = chunkStateSnapshots.getOrPut(record.id) { ConcurrentHashMap() }
            map[state.index] = state
        }
        val session = DownloadSession(record.request, record.resolution, Job(), CallTracker())
        val job = scope.launch(session.job) {
            runDownloadWithRetry(
                record.request,
                handle,
                record.resolution,
                startOffset = resumeBytes,
                callTracker = session.callTracker,
                extraListeners = listOf(progressTrackingListener),
                existingChunkStates = chunkStates,
                chunkStateUpdater = chunkStateUpdater
            )
        }
        activeSessions[record.id] = session.copy(job = job)
        watchSession(record.id, job)
        return true
    }

    private fun pathOwner(path: String, exceptId: String): OwnerRef? {
        for ((id, session) in activeSessions) {
            if (id != exceptId && canonicalPath(session.resolution.file) == path) {
                return OwnerRef(id, DownloadRecovery.RUNNING)
            }
        }
        for ((id, paused) in pausedStates) {
            if (id != exceptId && canonicalPath(paused.resolution.file) == path) {
                return OwnerRef(id, DownloadRecovery.PAUSED)
            }
        }
        return DownloadRecoveryStore.loadAll(appContext).firstOrNull { record ->
            record.id != exceptId &&
                (record.canonicalPath == path || canonicalPath(record.resolution.file) == path)
        }?.let { record -> OwnerRef(record.id, record.state) }
    }

    private fun dropAbandoned(id: String?) {
        if (id == null) return
        val session = synchronized(sessionLock) { activeSessions.remove(id) }
        session?.callTracker?.cancelAll()
        session?.job?.cancel(CancellationException("Replaced after the previous download failed"))
        pausedStates.remove(id)
        pendingDestinations.remove(id)
        chunkStateSnapshots.remove(id)
        DownloadConfigStore.removePausedState(appContext, id)
        DownloadRecoveryStore.delete(appContext, id)
        attemptGeneration[id] = (attemptGeneration[id] ?: 0L) + 1L
    }

    private fun nextGeneration(id: String): Long {
        val next = (attemptGeneration[id] ?: 0L) + 1L
        attemptGeneration[id] = next
        return next
    }

    private fun persistRecord(
        request: DownloadRequest,
        resolution: StorageResolution,
        state: String,
        generation: Long,
        scheduleRecovery: Boolean
    ) {
        if (attemptGeneration[request.id] != generation && state != DownloadRecovery.PAUSED) {
            return
        }
        val chunks = currentChunkStates(request.id)
        val bytes = if (chunks.isNotEmpty()) {
            chunks.totalCompletedBytes()
        } else {
            lastProgress[request.id] ?: 0L
        }
        val validators = artifactMeta[request.id]
        DownloadRecoveryStore.save(
            appContext,
            DownloadRecoveryRecord(
                id = request.id,
                request = request,
                resolution = resolution,
                state = state,
                completedBytes = bytes,
                chunkStates = chunks,
                strongEtag = validators?.strongEtag,
                lastModified = validators?.lastModified,
                totalBytes = validators?.totalBytes,
                generation = generation,
                canonicalPath = canonicalPath(resolution.file)
            )
        )
        if (scheduleRecovery && state in DownloadRecovery.RESUMABLE_AFTER_RESTART) {
            scheduler.ensureRecoveryScheduled()
        }
    }

    private fun rememberValidators(id: String, result: DownloadResult) {
        val current = artifactMeta[id]
        artifactMeta[id] = ArtifactValidators(
            strongEtag = result.strongEtag ?: current?.strongEtag,
            lastModified = result.lastModified ?: current?.lastModified,
            totalBytes = result.totalBytes ?: current?.totalBytes
        )
    }

    private fun resetPartial(file: File, handleId: String) {
        if (file.exists()) {
            RandomAccessFile(file, "rw").use { output -> output.setLength(0) }
        }
        chunkStateSnapshots.remove(handleId)
        lastProgress.remove(handleId)
        checkpointBytes.remove(handleId)
    }

    private fun markAbandoned(
        request: DownloadRequest,
        resolution: StorageResolution,
        generation: Long
    ) {
        if (attemptGeneration[request.id] != generation) return
        persistRecord(request, resolution, DownloadRecovery.FAILED, generation, false)
    }

    private fun markDownloadFinished(handleId: String) {
        if (!trackedIds.remove(handleId)) {
            return
        }
        var remaining = activeDownloads.decrementAndGet()
        if (remaining < 0) {
            activeDownloads.set(0)
            remaining = 0
        }
        if (remaining <= 0) {
            // Keep the completion or failure notification. stopService detaches the
            // service from that notification instead of dismissing the result.
            DownloadForegroundService.stopService(appContext)
        }
    }

    companion object {
        private const val TAG = "MobileDownloadManager"

        /**
         * 10. Creates an instance directly from a DownloadConfig.
         */
        fun create(context: Context, config: DownloadConfig = DownloadConfig()): MobileDownloadManager {
            return MobileDownloadManager(context, config)
        }

        /**
         * 11. Creates an instance using the fluent builder DSL.
         */
        fun create(context: Context, block: DownloadManagerBuilder.() -> Unit): MobileDownloadManager {
            return DownloadManagerBuilder(context).apply(block).build()
        }

        /**
         * 12. Exposes the builder for scenarios that need deferred building.
         */
        fun builder(context: Context): DownloadManagerBuilder {
            return DownloadManagerBuilder(context)
        }

        internal fun createRecovering(context: Context, config: DownloadConfig): MobileDownloadManager {
            return MobileDownloadManager(context, config, true)
        }

        internal fun createRecovering(
            context: Context,
            block: DownloadManagerBuilder.() -> Unit
        ): MobileDownloadManager {
            val config = DownloadManagerBuilder(context).apply(block).buildConfig()
            return MobileDownloadManager(context, config, true)
        }
    }
}

private data class OwnerRef(
    val id: String,
    val state: String
)

private data class DownloadSession(
    val request: DownloadRequest,
    val resolution: StorageResolution,
    val job: Job,
    val callTracker: CallTracker = CallTracker()
)

private data class PausedState(
    val request: DownloadRequest,
    val resolution: StorageResolution,
    val completedBytes: Long,
    val chunkStates: List<ChunkStateData>
)

internal class CallTracker {
    private val calls = ConcurrentHashMap.newKeySet<Call>()

    fun register(call: Call) {
        calls += call
    }

    fun cancelAll() {
        calls.forEach { it.cancel() }
        calls.clear()
    }
}

private fun List<ChunkStateData>.totalCompletedBytes(): Long {
    return sumOf { state ->
        max(0L, state.nextOffset - state.start)
    }
}

